network: ImprovedCAE
dataset: CIFAR10Dataset
save_location: "cifar10-v0.2"
flatten_size: "64 * 4 * 4" # 64 * 4 * 4 for MNIST(BaseCAE) # 64 * 4 * 4 for CIFAR10(BaseCAE)
color_channel: 3 # 1 for MNIST, 3 for CIFAR10
hidden_dim: 256
latent_dim: 128
lr: 0.00025
batch_size: 256
loss: MSE
optimizer: Adam
epoch: 100